should add functionality to add comments to an article - task 8
Jay7735/fe-nc-news pull request #5
Opened 2023-06-01 14:45 UTC by Jay7735

2023-06-01 15:49 UTC, Augs0 requested changes
This is looking great Jay well done! One tiny thing - could you hardcode the user so that comments can only come from someone 'logged in'? After that, I'm happy to approve!

2023-06-02 08:53 UTC, MRombi approved these changes
Please, apply the changes I mentioned and you are free to continue 🦾

2023-06-02 08:53 UTC, MRombi commented on fe-nc-news/src/AddComment.jsx
> +const AddComment = ({article_id}) => {
We might want to pass a state that allows us to update all the comments, at the moment when we write two new comments, the first one we wrote will not be rendered 🙂

2023-06-02 08:53 UTC, MRombi commented on fe-nc-news/src/AddComment.jsx
> +        // setCommentAuthor("")
We should remove comments 🙂

2023-06-02 08:53 UTC, MRombi commented on fe-nc-news/src/AddComment.jsx
> +            {/* <input type="text" value={commentAuthor} onChange={(event)=> setCommentAuthor(event.target.value)} required /> */}
We should remove comments 🙂

2023-06-02 12:45 UTC, Augs0 approved these changes
Great work, Jay! Have a think about how w could show the user their comment has been posted. It could be as simple as a paragraph that says comment posted or something

2023-06-02 12:45 UTC, Augs0 commented on fe-nc-news/src/Topics.jsx
> +import {React, useState, useEffect} from 'react'
I don't think we need the React import here

2023-06-02 12:45 UTC, Augs0 commented on fe-nc-news/src/styles/articles.css
>      /* //position abosloute position relative for link placement set bottom to zero  */
Don't forget to remove commented out code

2023-06-02 12:48 UTC, merged